### ISSUE TITLE
TODO-s

### ISSUE THREAD

**Issue by szepeviktor** [Manishearth/triomphe#69]
- [ ] when `byte_sub` is stabilized, this can accept T: ?Sized.
  https://github.com/Manishearth/triomphe/blob/1bce2664cd0e327b58b758a407871eec8343d05c/src/arc.rs#L82
- [ ] (bholley): Use the updated comment when [2] is merged.
  https://github.com/Manishearth/triomphe/blob/1bce2664cd0e327b58b758a407871eec8343d05c/src/arc.rs#L599
- [ ] should from_ref be relaxed to unsized types? It can't be
  https://github.com/Manishearth/triomphe/blob/1bce2664cd0e327b58b758a407871eec8343d05c/src/arc_borrow.rs#L47
- [ ] once `pointer::with_metadata_of` is stable or
  https://github.com/Manishearth/triomphe/blob/1bce2664cd0e327b58b758a407871eec8343d05c/src/header.rs#L212

Moving TODO-s to a GitHub issue, so contributors may see them.

**Comment by Manishearth** [comment]
I don't think this is helpful
